#!/usr/bin/env node
/**
 * Reads strings/weather.yaml and writes src/generated/weather_i18n_gen.{h,c}
 */
'use strict';

const fs = require('fs');
const path = require('path');
const yaml = require('yaml');

const ROOT = path.join(__dirname, '..');
const YAML_PATH = path.join(ROOT, 'strings', 'weather.yaml');
const OUT_DIR = path.join(ROOT, 'src', 'generated');
const HDR = path.join(OUT_DIR, 'weather_i18n_gen.h');
const SRC = path.join(OUT_DIR, 'weather_i18n_gen.c');

const LANG_IDS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];

function cEscape(s) {
  if (s == null) return '""';
  return (
    '"' +
    String(s)
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\r/g, '\\r')
      .replace(/\n/g, '\\n') +
    '"'
  );
}

function flattenLocale(entry) {
  if (entry && typeof entry === 'object' && entry['<<']) {
    const merged = { ...entry['<<'], ...entry };
    delete merged['<<'];
    return merged;
  }
  return entry;
}

function main() {
  const raw = fs.readFileSync(YAML_PATH, 'utf8');
  const doc = yaml.parse(raw);
  if (!doc || !doc.locales) {
    throw new Error('Invalid weather.yaml: missing locales');
  }

  const firstLang = String(LANG_IDS[0]);
  const sample = flattenLocale(doc.locales[firstLang]);
  const skyKeys = Object.keys(sample.sky || {})
    .map((k) => parseInt(k, 10))
    .filter((n) => !Number.isNaN(n))
    .sort((a, b) => a - b);

  const structFields = [];
  structFields.push('const char *sky_unknown;');
  for (const code of skyKeys) {
    structFields.push(`const char *sky_${code};`);
  }
  const tf = sample.temp_f;
  const tc = sample.temp_c;
  const q = sample.qual;
  const d = sample.decades;
  for (const k of Object.keys(tf)) {
    structFields.push(`const char *f_${k};`);
  }
  for (const k of Object.keys(tc)) {
    structFields.push(`const char *c_${k};`);
  }
  for (const k of Object.keys(q)) {
    structFields.push(`const char *q_${k};`);
  }
  for (const k of Object.keys(d)) {
    structFields.push(`const char *d_${k};`);
  }

  const structBody = structFields.map((l) => '  ' + l).join('\n');

  let header = `/* Generated by scripts/codegen-weather.js — do not edit. */
#pragma once
#include <stdint.h>

typedef struct WeatherLocale {
${structBody}
} WeatherLocale;

const WeatherLocale *weather_locale_for_lang(uint8_t lang);
const char *weather_sky_for_code(const WeatherLocale *L, int16_t code);
`;

  const inits = [];
  const fingerprints = {};
  const localeToCanonical = {};
  for (const lid of LANG_IDS) {
    const L = flattenLocale(doc.locales[String(lid)]);
    if (!L) {
      throw new Error(`Missing locale ${lid} in weather.yaml`);
    }
    const lines = [];
    lines.push(`  .sky_unknown = ${cEscape(L.sky_unknown)},`);
    for (const code of skyKeys) {
      const sk = L.sky || {};
      const v = sk[String(code)] ?? sk[code] ?? L.sky_unknown;
      lines.push(`  .sky_${code} = ${cEscape(v)},`);
    }
    for (const k of Object.keys(tf)) {
      lines.push(`  .f_${k} = ${cEscape(L.temp_f[k])},`);
    }
    for (const k of Object.keys(tc)) {
      lines.push(`  .c_${k} = ${cEscape(L.temp_c[k])},`);
    }
    for (const k of Object.keys(q)) {
      lines.push(`  .q_${k} = ${cEscape(L.qual[k])},`);
    }
    for (const k of Object.keys(d)) {
      lines.push(`  .d_${k} = ${cEscape(L.decades[k])},`);
    }
    const initStr = lines.join('\n');
    inits.push({ lid, initStr });

    const fingerprint = lines.join('|');
    if (!fingerprints[fingerprint]) {
      fingerprints[fingerprint] = lid;
    }
    localeToCanonical[lid] = fingerprints[fingerprint];
  }

  const uniqueInits = [];
  const emitted = new Set();
  for (const { lid, initStr } of inits) {
    const canonical = localeToCanonical[lid];
    if (!emitted.has(canonical)) {
      uniqueInits.push(`static const WeatherLocale WL_${canonical} = {\n${initStr}\n};`);
      emitted.add(canonical);
    }
  }

  const switchCases = skyKeys
    .map((code) => `    case ${code}: return L->sky_${code};`)
    .join('\n');

  const localeSwitch = LANG_IDS.map((lid) => {
    const canonical = localeToCanonical[lid];
    return `    case ${lid}: return &WL_${canonical};`;
  }).join('\n');

  const source = `/* Generated by scripts/codegen-weather.js — do not edit. */
#include "weather_i18n_gen.h"

${uniqueInits.join('\n\n')}

const WeatherLocale *weather_locale_for_lang(uint8_t lang) {
  switch (lang) {
${localeSwitch}
    default:
      return &WL_${localeToCanonical[2]};
  }
}

const char *weather_sky_for_code(const WeatherLocale *L, int16_t code) {
  switch (code) {
${switchCases}
    default:
      return L->sky_unknown;
  }
}
`;

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(HDR, header);
  fs.writeFileSync(SRC, source);
  console.error('Wrote', HDR, SRC);
}

main();
